const iconlist = [
  {
    img: "/recycle_icon.png",
    alt: "trash",
    title: "Recycling",
    active: false,
    minimized: false,
    content: "This is the window for Recycling",
  },
  {
    img: "/mail_icon.png",
    alt: "mail",
    title: "Mail",
    active: false,
    minimized: false,
    content: "This is the window for Mail",
  },
  {
    img: "/folder_icon.png",
    alt: "projects",
    title: "Projects",
    active: false,
    minimized: false,
    content: "This is the window for Projects",
  },
  {
    img: "/folder_icon.png",
    alt: "experience",
    title: "Experience",
    active: false,
    minimized: false,
    content: "This is the window for Experience",
  },
  {
    img: "/document_icon.png",
    alt: "resume",
    title: "Resume",
    active: false,
    minimized: false,
    content: "This is the window for Resume",
  },
  {
    img: "/document_icon.png",
    alt: "education",
    title: "Education",
    active: false,
    minimized: false,
    content: "This is the window for Education",
  },
  {
    img: "/document_icon.png",
    alt: "Test",
    title: "Test",
    active: false,
    minimized: false,
    content: "This is the window for Test",
  },
];

export default iconlist;
